(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(*Start timing*)
StartTime=AbsoluteTime[];
(*Load the package*)
Needs["xAct`HiGGS`"];
(*Build the HiGGS environment*)
BuildHiGGS[];
(*Define the theory*)
DefTheory[{Alp1==0,Alp2==0,Alp3==0,Alp4==0,Alp5==0,Alp6==0,Bet1==0,Bet2==0,cAlp1==0,cAlp2==0,cAlp3==0,cAlp4==0,cAlp5==0,cAlp6==0,cBet1==0,cBet2==0,cBet3==0}];

IndIfConstraints=ChangeFreeIndices[#,{-l,-m,-n}]&$IfConstraints;
(*Evaluate lots of Poisson brackets*)
PrimaryPoissonMatrix=Table[{$IfConstraints[ii],IndIfConstraints[jj],PoissonBracket[$IfConstraints[ii],IndIfConstraints[jj]]},{ii,Length@$IfConstraints},{jj,ii,Length@$IfConstraints}]

(*Evaluate some velocities*)
(*
Vel=Velocity[PhiB0p[]];
*)
(*Stop timing*)
EndTime=AbsoluteTime[];
TotTime=EndTime-StartTime;
Print["Time taken is: ",TotTime];
(**)
(*save to a mx cache*)
DumpSave[FileNameJoin@{Directory[],"tests.mx"},{TotTime,PrimaryPoissonMatrix}];
(**)
Quit[];



