(*===========================*)
(*  NesterFormIfConstraints  *)
(*===========================*)

Begin["xAct`HiGGS`Private`"];

NesterFormPhiB0pDefinition=ToNesterForm[PhiB0p[],ToShell->False];
Print[NesterFormPhiB0pDefinition];
ToNesterFormPhiB0p=MakeRule[{PhiB0p[],Evaluate[NesterFormPhiB0pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormPhiB1pDefinition=ToNesterForm[PhiB1p[-i,-j],ToShell->False];
Print[NesterFormPhiB1pDefinition];
ToNesterFormPhiB1p=MakeRule[{PhiB1p[-i,-j],Evaluate[NesterFormPhiB1pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormPhiB1mDefinition=ToNesterForm[PhiB1m[-i],ToShell->False];
Print[NesterFormPhiB1mDefinition];
ToNesterFormPhiB1m=MakeRule[{PhiB1m[-i],Evaluate[NesterFormPhiB1mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormPhiB2pDefinition=ToNesterForm[PhiB2p[-i,-j],ToShell->False];
Print[NesterFormPhiB2pDefinition];
ToNesterFormPhiB2p=MakeRule[{PhiB2p[-i,-j],Evaluate[NesterFormPhiB2pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormPhiA0pDefinition=ToNesterForm[PhiA0p[],ToShell->False];
Print[NesterFormPhiA0pDefinition];
ToNesterFormPhiA0p=MakeRule[{PhiA0p[],Evaluate[NesterFormPhiA0pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormPhiA0mDefinition=ToNesterForm[PhiA0m[],ToShell->False];
Print[NesterFormPhiA0mDefinition];
ToNesterFormPhiA0m=MakeRule[{PhiA0m[],Evaluate[NesterFormPhiA0mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormPhiA1pDefinition=ToNesterForm[PhiA1p[-i,-j],ToShell->False];
Print[NesterFormPhiA1pDefinition];
ToNesterFormPhiA1p=MakeRule[{PhiA1p[-i,-j],Evaluate[NesterFormPhiA1pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormPhiA1mDefinition=ToNesterForm[PhiA1m[-i],ToShell->False];
Print[NesterFormPhiA1mDefinition];
ToNesterFormPhiA1m=MakeRule[{PhiA1m[-i],Evaluate[NesterFormPhiA1mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormPhiA2pDefinition=ToNesterForm[PhiA2p[-i,-j],ToShell->False];
Print[NesterFormPhiA2pDefinition];
ToNesterFormPhiA2p=MakeRule[{PhiA2p[-i,-j],Evaluate[NesterFormPhiA2pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormPhiA2mDefinition=ToNesterForm[PhiA2m[-i,-j,-k],ToShell->False];
Print[NesterFormPhiA2mDefinition];
ToNesterFormPhiA2m=MakeRule[{PhiA2m[-i,-j,-k],Evaluate[NesterFormPhiA2mDefinition]},MetricOn->All,ContractMetrics->True];

PhiToNesterFormPhi=Join[ToNesterFormPhiB0p,ToNesterFormPhiB1p,ToNesterFormPhiB1m,ToNesterFormPhiB2p,ToNesterFormPhiA0p,ToNesterFormPhiA0m,ToNesterFormPhiA1p,ToNesterFormPhiA1m,ToNesterFormPhiA2p,ToNesterFormPhiA2m];

NesterFormChiPerpB0pDefinition=ToNesterForm[ChiPerpB0p[],ToShell->False];
Print[NesterFormChiPerpB0pDefinition];
ToNesterFormChiPerpB0p=MakeRule[{ChiPerpB0p[],Evaluate[NesterFormChiPerpB0pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiPerpB1pDefinition=ToNesterForm[ChiPerpB1p[-i,-j],ToShell->False];
Print[NesterFormChiPerpB1pDefinition];
ToNesterFormChiPerpB1p=MakeRule[{ChiPerpB1p[-i,-j],Evaluate[NesterFormChiPerpB1pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiPerpB1mDefinition=ToNesterForm[ChiPerpB1m[-i],ToShell->False];
Print[NesterFormChiPerpB1mDefinition];
ToNesterFormChiPerpB1m=MakeRule[{ChiPerpB1m[-i],Evaluate[NesterFormChiPerpB1mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiPerpB2pDefinition=ToNesterForm[ChiPerpB2p[-i,-j],ToShell->False];
Print[NesterFormChiPerpB2pDefinition];
ToNesterFormChiPerpB2p=MakeRule[{ChiPerpB2p[-i,-j],Evaluate[NesterFormChiPerpB2pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiPerpA0pDefinition=ToNesterForm[ChiPerpA0p[],ToShell->False];
Print[NesterFormChiPerpA0pDefinition];
ToNesterFormChiPerpA0p=MakeRule[{ChiPerpA0p[],Evaluate[NesterFormChiPerpA0pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiPerpA0mDefinition=ToNesterForm[ChiPerpA0m[],ToShell->False];
Print[NesterFormChiPerpA0mDefinition];
ToNesterFormChiPerpA0m=MakeRule[{ChiPerpA0m[],Evaluate[NesterFormChiPerpA0mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiPerpA1pDefinition=ToNesterForm[ChiPerpA1p[-i,-j],ToShell->False];
Print[NesterFormChiPerpA1pDefinition];
ToNesterFormChiPerpA1p=MakeRule[{ChiPerpA1p[-i,-j],Evaluate[NesterFormChiPerpA1pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiPerpA1mDefinition=ToNesterForm[ChiPerpA1m[-i],ToShell->False];
Print[NesterFormChiPerpA1mDefinition];
ToNesterFormChiPerpA1m=MakeRule[{ChiPerpA1m[-i],Evaluate[NesterFormChiPerpA1mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiPerpA2pDefinition=ToNesterForm[ChiPerpA2p[-i,-j],ToShell->False];
Print[NesterFormChiPerpA2pDefinition];
ToNesterFormChiPerpA2p=MakeRule[{ChiPerpA2p[-i,-j],Evaluate[NesterFormChiPerpA2pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiPerpA2mDefinition=ToNesterForm[ChiPerpA2m[-i,-j,-k],ToShell->False];
Print[NesterFormChiPerpA2mDefinition];
ToNesterFormChiPerpA2m=MakeRule[{ChiPerpA2m[-i,-j,-k],Evaluate[NesterFormChiPerpA2mDefinition]},MetricOn->All,ContractMetrics->True];

ChiPerpToNesterFormChiPerp=Join[ToNesterFormChiPerpB0p,ToNesterFormChiPerpB1p,ToNesterFormChiPerpB1m,ToNesterFormChiPerpB2p,ToNesterFormChiPerpA0p,ToNesterFormChiPerpA0m,ToNesterFormChiPerpA1p,ToNesterFormChiPerpA1m,ToNesterFormChiPerpA2p,ToNesterFormChiPerpA2m];

NesterFormChiParaB0mDefinition=ToNesterForm[ChiParaB0m[],ToShell->False];
Print[NesterFormChiParaB0mDefinition];
ToNesterFormChiParaB0m=MakeRule[{ChiParaB0m[],Evaluate[NesterFormChiParaB0mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiParaB1pDefinition=ToNesterForm[ChiParaB1p[-i,-j],ToShell->False];
Print[NesterFormChiParaB1pDefinition];
ToNesterFormChiParaB1p=MakeRule[{ChiParaB1p[-i,-j],Evaluate[NesterFormChiParaB1pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiParaB1mDefinition=ToNesterForm[ChiParaB1m[-i],ToShell->False];
Print[NesterFormChiParaB1mDefinition];
ToNesterFormChiParaB1m=MakeRule[{ChiParaB1m[-i],Evaluate[NesterFormChiParaB1mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiParaB2mDefinition=ToNesterForm[ChiParaB2m[-i,-j,-k],ToShell->False];
Print[NesterFormChiParaB2mDefinition];
ToNesterFormChiParaB2m=MakeRule[{ChiParaB2m[-i,-j,-k],Evaluate[NesterFormChiParaB2mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiParaA0pDefinition=ToNesterForm[ChiParaA0p[],ToShell->False];
Print[NesterFormChiParaA0pDefinition];
ToNesterFormChiParaA0p=MakeRule[{ChiParaA0p[],Evaluate[NesterFormChiParaA0pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiParaA0mDefinition=ToNesterForm[ChiParaA0m[],ToShell->False];
Print[NesterFormChiParaA0mDefinition];
ToNesterFormChiParaA0m=MakeRule[{ChiParaA0m[],Evaluate[NesterFormChiParaA0mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiParaA1pDefinition=ToNesterForm[ChiParaA1p[-i,-j],ToShell->False];
Print[NesterFormChiParaA1pDefinition];
ToNesterFormChiParaA1p=MakeRule[{ChiParaA1p[-i,-j],Evaluate[NesterFormChiParaA1pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiParaA1mDefinition=ToNesterForm[ChiParaA1m[-i],ToShell->False];
Print[NesterFormChiParaA1mDefinition];
ToNesterFormChiParaA1m=MakeRule[{ChiParaA1m[-i],Evaluate[NesterFormChiParaA1mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiParaA2pDefinition=ToNesterForm[ChiParaA2p[-i,-j],ToShell->False];
Print[NesterFormChiParaA2pDefinition];
ToNesterFormChiParaA2p=MakeRule[{ChiParaA2p[-i,-j],Evaluate[NesterFormChiParaA2pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiParaA2mDefinition=ToNesterForm[ChiParaA2m[-i,-j,-k],ToShell->False];
Print[NesterFormChiParaA2mDefinition];
ToNesterFormChiParaA2m=MakeRule[{ChiParaA2m[-i,-j,-k],Evaluate[NesterFormChiParaA2mDefinition]},MetricOn->All,ContractMetrics->True];

ChiParaToNesterFormChiPara=Join[ToNesterFormChiParaB0m,ToNesterFormChiParaB1p,ToNesterFormChiParaB1m,ToNesterFormChiParaB2m,ToNesterFormChiParaA0p,ToNesterFormChiParaA0m,ToNesterFormChiParaA1p,ToNesterFormChiParaA1m,ToNesterFormChiParaA2p,ToNesterFormChiParaA2m];

NesterFormChiSingB1pDefinition=ToNesterForm[ChiSingB1p[-i,-j],ToShell->False];
Print[NesterFormChiSingB1pDefinition];
ToNesterFormChiSingB1p=MakeRule[{ChiSingB1p[-i,-j],Evaluate[NesterFormChiSingB1pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiSingB1mDefinition=ToNesterForm[ChiSingB1m[-i],ToShell->False];
Print[NesterFormChiSingB1mDefinition];
ToNesterFormChiSingB1m=MakeRule[{ChiSingB1m[-i],Evaluate[NesterFormChiSingB1mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiSingA0pDefinition=ToNesterForm[ChiSingA0p[],ToShell->False];
Print[NesterFormChiSingA0pDefinition];
ToNesterFormChiSingA0p=MakeRule[{ChiSingA0p[],Evaluate[NesterFormChiSingA0pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiSingA0mDefinition=ToNesterForm[ChiSingA0m[],ToShell->False];
Print[NesterFormChiSingA0mDefinition];
ToNesterFormChiSingA0m=MakeRule[{ChiSingA0m[],Evaluate[NesterFormChiSingA0mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiSingA1pDefinition=ToNesterForm[ChiSingA1p[-i,-j],ToShell->False];
Print[NesterFormChiSingA1pDefinition];
ToNesterFormChiSingA1p=MakeRule[{ChiSingA1p[-i,-j],Evaluate[NesterFormChiSingA1pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiSingA1mDefinition=ToNesterForm[ChiSingA1m[-i],ToShell->False];
Print[NesterFormChiSingA1mDefinition];
ToNesterFormChiSingA1m=MakeRule[{ChiSingA1m[-i],Evaluate[NesterFormChiSingA1mDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiSingA2pDefinition=ToNesterForm[ChiSingA2p[-i,-j],ToShell->False];
Print[NesterFormChiSingA2pDefinition];
ToNesterFormChiSingA2p=MakeRule[{ChiSingA2p[-i,-j],Evaluate[NesterFormChiSingA2pDefinition]},MetricOn->All,ContractMetrics->True];
NesterFormChiSingA2mDefinition=ToNesterForm[ChiSingA2m[-i,-j,-k],ToShell->False];
Print[NesterFormChiSingA2mDefinition];
ToNesterFormChiSingA2m=MakeRule[{ChiSingA2m[-i,-j,-k],Evaluate[NesterFormChiSingA2mDefinition]},MetricOn->All,ContractMetrics->True];

ChiSingToNesterFormChiSing=Join[ToNesterFormChiSingB1p,ToNesterFormChiSingB1m,ToNesterFormChiSingA0p,ToNesterFormChiSingA0m,ToNesterFormChiSingA1p,ToNesterFormChiSingA1m,ToNesterFormChiSingA2p,ToNesterFormChiSingA2m];

DumpSave[xAct`HiGGS`Private`BinaryLocation["NesterFormIfConstraints"],{PhiToNesterFormPhi,ChiPerpToNesterFormChiPerp,ChiParaToNesterFormChiPara,ChiSingToNesterFormChiSing}];

End[];
